### ISSUE TITLE
Cannot compile successfully.

### ISSUE THREAD

**Issue by SatellaPoi** [tabrezm/r8125-synology#1]
![WX20230718-152448@2x](https://github.com/tabrezm/r8125-synology/assets/44998959/189be507-0f27-48b4-aee3-cba271c73d99)
Synology SA6400 (epyc7002)
DSM 7.1 (Linux 5.10.55)

https://github.com/awesometic/realtek-r8125-dkms/commit/44b781e5b79741f56325d6aaa126ae8bd39d467f
I initially wanted to fix this bug that's causing the network speed to display incorrectly. If it's possible, could you assist me in compiling a driver? I would greatly appreciate it!

**Comment by tabrezm** [comment]
I can repro this error. You need to do two things to get the driver to compile successfully:

1. Comment out `#define CONFIG_CC_HAS_ASM_INLINE` in `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build/include/generated/autoconf.h`. The included version of gcc is too old to support this, even if you try using `/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cc`.
2. `epyc7002` has a newer kernel version than `avoton`, so you don't need the workarounds included in this repository. Use the original source files [here](https://github.com/tabrezm/r8125-synology/files/12091638/r8125-9.009.02.zip) with my custom Makefile.

Successful make log:
```
sh-4.3# make
find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net/ethernet': No such file or directory
find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net': No such file or directory

CC:  cc
CCVERSION:  4.9.2
BASEDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1
DRIVERDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net
PWD:  /usr/src/r8125

make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 clean
make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 modules
make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
  CC [M]  /usr/src/r8125/r8125_n.o
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_get_settings()+0x8: indirect call found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_netpoll()+0x3e: indirect call found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_set_speed.part.54()+0x13: indirect jump found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ac: indirect call found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ef: indirect call found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_up()+0x24a: indirect call found in RETPOLINE build
/usr/src/r8125/r8125_n.o: warning: objtool: _rtl8125_check_link_status()+0xc: indirect call found in RETPOLINE build
  CC [M]  /usr/src/r8125/rtl_eeprom.o
  CC [M]  /usr/src/r8125/rtltool.o
  LD [M]  /usr/src/r8125/r8125.o
  MODPOST /usr/src/r8125/Module.symvers
  CC [M]  /usr/src/r8125/r8125.mod.o
  LD [M]  /usr/src/r8125/r8125.ko
make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
```

**Comment by SatellaPoi** [comment]
Thanks.

**Comment by FelixLAI85** [comment]
> I can repro this error. You need to do two things to get the driver to compile successfully:
> 
> 1. Comment out `#define CONFIG_CC_HAS_ASM_INLINE` in `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build/include/generated/autoconf.h`. The included version of gcc is too old to support this, even if you try using `/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cc`.
> 2. `epyc7002` has a newer kernel version than `avoton`, so you don't need the workarounds included in this repository. Use the original source files [here](https://github.com/tabrezm/r8125-synology/files/12091638/r8125-9.009.02.zip) with my custom Makefile.
> 
> Successful make log:
> 
> ```
> sh-4.3# make
> find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net/ethernet': No such file or directory
> find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net': No such file or directory
> 
> CC:  cc
> CCVERSION:  4.9.2
> BASEDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1
> DRIVERDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net
> PWD:  /usr/src/r8125
> 
> make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 clean
> make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 modules
> make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
>   CC [M]  /usr/src/r8125/r8125_n.o
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_get_settings()+0x8: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_netpoll()+0x3e: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_set_speed.part.54()+0x13: indirect jump found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ac: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ef: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_up()+0x24a: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: _rtl8125_check_link_status()+0xc: indirect call found in RETPOLINE build
>   CC [M]  /usr/src/r8125/rtl_eeprom.o
>   CC [M]  /usr/src/r8125/rtltool.o
>   LD [M]  /usr/src/r8125/r8125.o
>   MODPOST /usr/src/r8125/Module.symvers
>   CC [M]  /usr/src/r8125/r8125.mod.o
>   LD [M]  /usr/src/r8125/r8125.ko
> make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> ```
Hi Tabrezm, I followed your modification on this post to complie the drver for epyc7002 but got some error, could you give me some tips to solve these issues? Thanks.
` find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/kernel/drivers/net/ethernet': No such file or directory                find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/kernel/drivers/net': No such file or directory                               ] 0%                                           ] 0%                                           ] 0%                                                          CC:  cc                                 ] 0%                                           ] 0%                                                                       CCVERSION:  4.9.2          ] 0%                                           ] 0%                                                                                    BASEDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2                                                                     DRIVERDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/kernel/drivers/net                                                PWD:  /usr/src/r8125-009/src       ] 0%                                           ] 0%                                                                                                  ] 0%                                           ] 0%                                                                                         make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build M=/usr/src/r8125-009/src clean                                  make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build'                                           make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build'                                            make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build M=/usr/src/r8125-009/src modules                                make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build'
  CC [M]  /usr/src/r8125-009/src/r8125_n.o
In file included from ././include/linux/kconfig.h:7:0,
                 from <command-line>:0:
./include/generated/autoconf.h:521:1: error: stray '##' in program
 ##define CONFIG_CC_HAS_ASM_INLINE 1
 ^
./include/generated/autoconf.h:521:3: error: unknown type name 'define'
 ##define CONFIG_CC_HAS_ASM_INLINE 1
   ^
./include/generated/autoconf.h:521:35: error: expected '=', ',', ';', 'asm' or '__attribute__' before numeric constant
 ##define CONFIG_CC_HAS_ASM_INLINE 1
                                   ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:109:28: error: field 'data' has incomplete type
  struct ftrace_branch_data data;
                            ^
scripts/Makefile.build:280: recipe for target '/usr/src/r8125-009/src/r8125_n.o' failed
make[2]: *** [/usr/src/r8125-009/src/r8125_n.o] Error 1
Makefile:1822: recipe for target '/usr/src/r8125-009/src' failed
make[1]: *** [/usr/src/r8125-009/src] Error 2
make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.2/build'
Makefile:151: recipe for target 'modules' failed
make: *** [modules] Error 2
`

**Comment by FelixLAI85** [comment]
> I can repro this error. You need to do two things to get the driver to compile successfully:
> 
> 1. Comment out `#define CONFIG_CC_HAS_ASM_INLINE` in `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build/include/generated/autoconf.h`. The included version of gcc is too old to support this, even if you try using `/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cc`.
> 2. `epyc7002` has a newer kernel version than `avoton`, so you don't need the workarounds included in this repository. Use the original source files [here](https://github.com/tabrezm/r8125-synology/files/12091638/r8125-9.009.02.zip) with my custom Makefile.
> 
> Successful make log:
> 
> ```
> sh-4.3# make
> find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net/ethernet': No such file or directory
> find: `/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net': No such file or directory
> 
> CC:  cc
> CCVERSION:  4.9.2
> BASEDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1
> DRIVERDIR:  /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/kernel/drivers/net
> PWD:  /usr/src/r8125
> 
> make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 clean
> make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> make -C /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build M=/usr/src/r8125 modules
> make[1]: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
>   CC [M]  /usr/src/r8125/r8125_n.o
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_get_settings()+0x8: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_netpoll()+0x3e: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_set_speed.part.54()+0x13: indirect jump found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ac: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_powerdown_pll()+0x1ef: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: rtl8125_up()+0x24a: indirect call found in RETPOLINE build
> /usr/src/r8125/r8125_n.o: warning: objtool: _rtl8125_check_link_status()+0xc: indirect call found in RETPOLINE build
>   CC [M]  /usr/src/r8125/rtl_eeprom.o
>   CC [M]  /usr/src/r8125/rtltool.o
>   LD [M]  /usr/src/r8125/r8125.o
>   MODPOST /usr/src/r8125/Module.symvers
>   CC [M]  /usr/src/r8125/r8125.mod.o
>   LD [M]  /usr/src/r8125/r8125.ko
> make[1]: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
> ```
Hi Tabrezm, I followed your modification on this post to complie the drver for epyc7002 but got some error, could you give me some tips to solve these issues? Thanks.
![1](https://github.com/tabrezm/r8125-synology/assets/42988035/f2b82d4f-d72b-4a2e-8113-d41db6cf7cca)
